export type ManifestFormat = "hls" | "dash";
export type UploadMethod = "tus" | "multipart";

export type ProviderCapabilities = Readonly<{
  durableStorage: boolean;
  multiRenditionTranscoding: boolean;
  manifestFormats: readonly ManifestFormat[];
  cdnDelivery: boolean;
  uploadMethods: readonly UploadMethod[];
  signedPlaybackUrls: boolean;
  encodeCompletionCallback: boolean;
}>;

/**
 * Describes whether this adapter has been configured, not the health of an
 * external provider service.
 */
export type ProviderAvailability =
  | Readonly<{ state: "configured" }>
  | Readonly<{ state: "unavailable"; reason: "not_configured" }>;

export type TenantSpace = {
  id: string;
};

/** A provider received and rejected a create request; no tenant space was created. */
export class TenantSpaceCreationRejectedError extends Error {
  constructor(message: string, options?: ErrorOptions) {
    super(message, options);
    this.name = "TenantSpaceCreationRejectedError";
  }
}

/** A provider definitively rejected asset creation, so its local reservation may be removed. */
export class AssetCreationRejectedError extends Error {
  constructor(message: string, options?: ErrorOptions) {
    super(message, options);
    this.name = "AssetCreationRejectedError";
  }
}

/**
 * A provider definitively rejected callback configuration. The tenant space
 * exists, but it must not be activated until callback configuration is repaired.
 */
export class EncodeCompletionCallbackRejectedError extends Error {
  constructor(message: string, options?: ErrorOptions) {
    super(message, options);
    this.name = "EncodeCompletionCallbackRejectedError";
  }
}

export type Asset = {
  id: string;
};

export type AssetStatus =
  | { state: "created" | "uploading" | "processing" }
  | { state: "ready"; durationSeconds: number }
  | { state: "error"; reason: string };

export type TusUploadCredentials = {
  kind: "tus";
  endpoint: string;
  headers: Readonly<Record<string, string>>;
  expiresAt: string;
};

export type MultipartUploadCredentials = {
  kind: "multipart";
  uploadId: string;
  partSizeBytes: number;
  parts: ReadonlyArray<{
    number: number;
    url: string;
    headers: Readonly<Record<string, string>>;
  }>;
  completeUrl: string;
  expiresAt: string;
};

export type UploadCredentials = TusUploadCredentials | MultipartUploadCredentials;

export type PlaybackSources = {
  hlsUrl?: string;
  dashUrl?: string;
  posterUrl?: string;
  expiresAt: string;
};

export type EncodeCompletionEvent = {
  eventId: string;
  tenantSpaceId: string;
  assetId: string;
  status: Extract<AssetStatus, { state: "ready" | "error" }>;
  occurredAt: string;
};

export interface VideoProvider {
  readonly key: string;
  readonly availability: ProviderAvailability;
  readonly capabilities: ProviderCapabilities;

  createTenantSpace(input: { name: string }): Promise<TenantSpace>;
  setEncodeCompletionCallback(space: TenantSpace, webhookUrl: string): Promise<void>;
  deleteTenantSpace(space: TenantSpace): Promise<void>;
  createAsset(space: TenantSpace, input: { title: string }): Promise<Asset>;
  getUploadCredentials(
    space: TenantSpace,
    asset: Asset,
    input: { fileName: string; contentType: string; contentLength: number },
  ): Promise<UploadCredentials>;
  getAssetStatus(space: TenantSpace, asset: Asset): Promise<AssetStatus>;
  deleteAsset(space: TenantSpace, asset: Asset): Promise<void>;
  getPlaybackSources(space: TenantSpace, asset: Asset): Promise<PlaybackSources>;
  /**
   * Confirms that a playback URL generated by this adapter is safe to serve for
   * the supplied tenant space and asset. This is configuration-scoped and never
   * performs network or DNS lookups.
   */
  isPlaybackSourceTrusted(space: TenantSpace, asset: Asset, url: string): Promise<boolean>;
  verifyEncodeCompletionCallback(
    rawBody: Buffer,
    headers: Readonly<Record<string, string | string[] | undefined>>,
  ): EncodeCompletionEvent | null;
}