export const TENANT_RLS_TABLES = [
  "organizations",
  "organization_customization",
  "users",
  "permission_groups",
  "group_permissions",
  "memberships",
  "invitations",
  "folders",
  "videos",
  "video_embeds",
  "video_analytics_rollups",
  "playback_events",
  "provider_accounts",
  "provider_tenant_spaces",
  "organization_entitlement_overrides",
  "webhook_events",
  "embed_generation_outbox",
  "audit_logs",
  "thumbnail_upload_intents",
  "object_cleanup_outbox",
  "organization_billing",
  "billing_operations",
  "billing_event_receipts",
  "analytics_dirty_days",
  "analytics_rate_windows",
  "analytics_playback_sessions",
  "onboarding_provisioning_intents",
  "custom_domains",
  "custom_domain_verification_windows",
  "master_storage_operations",
] as const;

export const APP_TABLE_PRIVILEGES: Record<string, readonly string[]> = {
  analytics_dirty_days: ["DELETE", "INSERT", "SELECT", "UPDATE"],
  analytics_playback_sessions: ["INSERT", "SELECT", "UPDATE"],
  analytics_rate_windows: ["DELETE", "INSERT", "SELECT", "UPDATE"],
  audit_logs: ["INSERT", "SELECT"],
  billing_event_receipts: ["INSERT", "SELECT", "UPDATE"],
  billing_operations: ["INSERT", "SELECT", "UPDATE"],
  custom_domain_verification_windows: ["INSERT", "SELECT", "UPDATE"],
  custom_domains: ["DELETE", "INSERT", "SELECT", "UPDATE"],
  embed_generation_outbox: ["INSERT", "SELECT", "UPDATE"],
  folders: ["DELETE", "INSERT", "SELECT", "UPDATE"],
  group_permissions: ["DELETE", "INSERT", "SELECT"],
  invitations: ["DELETE", "INSERT", "SELECT", "UPDATE"],
  master_storage_operations: ["INSERT", "SELECT", "UPDATE"],
  memberships: ["INSERT", "SELECT", "UPDATE"],
  object_cleanup_outbox: ["INSERT", "SELECT", "UPDATE"],
  onboarding_provisioning_intents: ["INSERT", "SELECT", "UPDATE"],
  organization_billing: ["INSERT", "SELECT", "UPDATE"],
  organization_customization: ["INSERT", "SELECT", "UPDATE"],
  organization_entitlement_overrides: ["SELECT"],
  organizations: ["INSERT", "SELECT", "UPDATE"],
  permission_groups: ["DELETE", "INSERT", "SELECT", "UPDATE"],
  permissions: ["INSERT", "SELECT"],
  plans: ["SELECT"],
  playback_events: ["INSERT", "SELECT"],
  provider_accounts: ["SELECT"],
  schema_migrations: ["SELECT"],
  provider_tenant_spaces: ["DELETE", "INSERT", "SELECT", "UPDATE"],
  thumbnail_upload_intents: ["DELETE", "INSERT", "SELECT", "UPDATE"],
  users: ["SELECT"],
  video_analytics_rollups: ["INSERT", "SELECT"],
  video_embeds: ["DELETE", "INSERT", "SELECT", "UPDATE"],
  videos: ["DELETE", "INSERT", "SELECT", "UPDATE"],
  webhook_events: ["INSERT", "SELECT", "UPDATE"],
};

export const WORKER_TABLE_PRIVILEGES: Record<string, readonly string[]> = {
  analytics_dirty_days: ["DELETE", "SELECT", "UPDATE"],
  analytics_playback_sessions: ["DELETE", "SELECT"],
  analytics_rate_windows: ["DELETE", "SELECT"],
  audit_logs: ["INSERT"],
  custom_domain_verification_windows: ["SELECT", "UPDATE"],
  custom_domains: ["SELECT", "UPDATE"],
  embed_generation_outbox: ["SELECT", "UPDATE"],
  group_permissions: ["INSERT", "SELECT"],
  master_storage_operations: ["SELECT", "UPDATE"],
  object_cleanup_outbox: ["DELETE", "INSERT", "SELECT"],
  onboarding_provisioning_intents: ["SELECT", "UPDATE"],
  organization_billing: ["SELECT", "UPDATE"],
  organization_customization: ["INSERT", "SELECT", "UPDATE"],
  organizations: ["SELECT", "UPDATE"],
  permission_groups: ["INSERT", "SELECT"],
  permissions: ["INSERT", "SELECT"],
  plans: ["SELECT"],
  playback_events: ["DELETE", "SELECT"],
  provider_accounts: ["SELECT", "UPDATE"],
  provider_tenant_spaces: ["DELETE", "INSERT", "SELECT", "UPDATE"],
  thumbnail_upload_intents: ["DELETE", "SELECT"],
  video_analytics_rollups: ["INSERT", "SELECT", "UPDATE"],
  video_embeds: ["INSERT", "SELECT", "UPDATE"],
  videos: ["SELECT", "UPDATE"],
};

export const WORKER_COLUMN_PRIVILEGES: Record<string, readonly string[]> = {
  "object_cleanup_outbox.UPDATE": [
    "attempts",
    "completed_at",
    "last_error",
    "next_attempt_at",
    "quarantined_at",
    "updated_at",
  ],
};