import pg from "pg";
import { catalogFingerprint, EXPECTED_CATALOG_HASHES } from "./catalog.ts";
import { createHash } from "node:crypto";
import { readFile, readdir } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
const { Client } = pg;
const tables = ["plans","organizations","organization_customization","users","sessions","accounts","verifications","permission_groups","permissions","group_permissions","memberships","invitations","provider_accounts","provider_tenant_spaces","organization_entitlement_overrides","webhook_events","embed_generation_outbox","audit_logs","folders","videos","video_embeds","video_analytics_rollups","playback_events","thumbnail_upload_intents","object_cleanup_outbox","organization_billing","billing_operations","billing_event_receipts","analytics_dirty_days","analytics_rate_windows","analytics_playback_sessions","onboarding_provisioning_intents","custom_domains","custom_domain_verification_windows","master_storage_operations"];
const columns = ["videos.thumbnail_object_key","videos.thumbnail_content_type","videos.thumbnail_size_bytes","videos.master_sha256","videos.master_size_bytes","videos.master_content_type","object_cleanup_outbox.quarantined_at","playback_events.event_id","playback_events.embed_id","playback_events.received_at","video_analytics_rollups.unique_sessions","video_analytics_rollups.completions","audit_logs.actor_kind","audit_logs.category","audit_logs.before_state","audit_logs.after_state","audit_logs.request_id","onboarding_provisioning_intents.requested_by_user_id","onboarding_provisioning_intents.dispatch_claim","custom_domains.hostname","custom_domains.challenge_value","custom_domains.lifecycle_state","master_storage_operations.operation","master_storage_operations.restore_storage_key","master_storage_operations.restore_sha256","master_storage_operations.restore_size_bytes","master_storage_operations.restore_content_type","master_storage_operations.idempotency_key","master_storage_operations.dispatch_generation","permission_groups.system_key","invitations.revoked_at","invitations.delivered_at","invitations.accepted_by_user_id"];
const indexes = ["videos_org_created_idx","videos_thumbnail_metadata_check","thumbnail_upload_intents_object_key_idx","thumbnail_upload_intents_video_idx","thumbnail_upload_intents_expiry_idx","object_cleanup_outbox_object_key_idx","object_cleanup_outbox_pending_idx","playback_events_org_event_idx","video_rollups_org_video_day_idx","analytics_dirty_days_available_idx","analytics_rate_windows_expiry_idx","audit_logs_org_time_idx","audit_logs_org_category_time_idx","audit_logs_org_subject_time_idx","audit_logs_org_actor_time_idx","onboarding_intents_org_idx","onboarding_intents_dispatch_idx","onboarding_intents_user_idx","custom_domains_one_active_org_idx","custom_domains_unique_active_hostname_idx","custom_domains_worker_idx","videos_id_organization_identity_idx","master_storage_operations_video_organization_fk","master_storage_operations_idempotency_idx","master_storage_operations_one_active_video_idx","master_storage_operations_dispatch_idx","permission_groups_org_system_key_idx","memberships_org_group_fk","invitations_org_group_fk","invitations_pending_org_email_idx"];
const rls = ["organization_customization","permission_groups","group_permissions","memberships","invitations","folders","videos","thumbnail_upload_intents","video_analytics_rollups","playback_events","provider_tenant_spaces","organization_entitlement_overrides","audit_logs","organization_billing","billing_operations","billing_event_receipts","analytics_dirty_days","analytics_rate_windows","analytics_playback_sessions","onboarding_provisioning_intents","custom_domains","custom_domain_verification_windows","master_storage_operations"];
async function main() {
  if (!process.env.DATABASE_URL) throw new Error("DATABASE_URL is required");
  const client = new Client({ connectionString: process.env.DATABASE_URL }); await client.connect();
  try {
    const relation = await client.query<{ relname: string }>("select relname from pg_class join pg_namespace n on n.oid=relnamespace where n.nspname='public' and relkind='r'");
    const present = new Set(relation.rows.map((r) => r.relname));
    for (const table of tables) if (!present.has(table)) throw new Error(`missing required table public.${table}`);
    for (const item of columns) { const [table, column] = item.split("."); const q = await client.query("select 1 from information_schema.columns where table_schema='public' and table_name=$1 and column_name=$2", [table, column]); if (!q.rowCount) throw new Error(`missing ${item}`); }
    for (const name of indexes) { const q = await client.query("select 1 from pg_class where relname=$1 union all select 1 from pg_constraint where conname=$1", [name]); if (!q.rowCount) throw new Error(`missing required index or constraint ${name}`); }
    for (const table of rls) { const q = await client.query<{ relrowsecurity: boolean }>("select relrowsecurity from pg_class where oid=$1::regclass", [`public.${table}`]); if (q.rows[0]?.relrowsecurity !== true) throw new Error(`RLS is not enabled on ${table}`); const p = await client.query("select 1 from pg_policies where schemaname='public' and tablename=$1 and policyname='tenant_isolation' and 'vid_app'=any(roles)", [table]); if (!p.rowCount) throw new Error(`vid_app tenant_isolation policy missing on ${table}`); }
    const auditGrant = await client.query<{ ok: boolean }>("select has_table_privilege('vid_app','public.audit_logs','select,insert') and not has_table_privilege('vid_app','public.audit_logs','update') and not has_table_privilege('vid_app','public.audit_logs','delete') as ok");
    if (!auditGrant.rows[0]?.ok) throw new Error("vid_app audit_logs must be append-only");
    const invitationLookup = await client.query<{ ok: boolean }>("select to_regprocedure('public.lookup_acceptable_invitation(text,text)') is not null and has_function_privilege('vid_app','public.lookup_acceptable_invitation(text,text)','execute') as ok");
    if (!invitationLookup.rows[0]?.ok) throw new Error("vid_app invitation lookup capability is missing");
    const boss = await client.query<{ version: number }>("select version from vid_jobs.version");
    if (boss.rows.length !== 1 || boss.rows[0]?.version !== 39) throw new Error("vid_jobs must be pg-boss 12.29.0 schema version 39");
    for (const object of ["job","job_common","job_dependency","queue","schedule","subscription","version","bam"]) { const q = await client.query("select 1 from pg_class join pg_namespace n on n.oid=relnamespace where n.nspname='vid_jobs' and relname=$1", [object]); if (!q.rowCount) throw new Error(`missing pg-boss managed object vid_jobs.${object}`); }
    const bossGrant = await client.query<{ ok: boolean }>("select has_schema_privilege('vid_app','vid_jobs','usage') and has_table_privilege('vid_app','vid_jobs.job','select,insert,update,delete') as ok");
    if (!bossGrant.rows[0]?.ok) throw new Error("vid_app is missing required vid_jobs runtime grants");
    const final = await catalogFingerprint(client, "g1Identity");
    if (EXPECTED_CATALOG_HASHES.g1Identity.startsWith("REPLACE_")) throw new Error("g1Identity catalog hash is unset; run accept-migrations on an isolated database and record its hash");
    if (final.hash !== EXPECTED_CATALOG_HASHES.g1Identity) throw new Error(`g1 identity catalog fingerprint mismatch: ${final.hash}`);
    const dir = join(dirname(fileURLToPath(import.meta.url)), "..", "migrations");
    const files = (await readdir(dir)).filter((name) => /^\d{4}_.+\.sql$/.test(name)).sort();
    const ledger = await client.query<{ name: string; checksum: string }>("select name,checksum from public.schema_migrations order by name");
    if (ledger.rows.length !== files.length) throw new Error("migration ledger set differs from repository");
    for (const [index, name] of files.entries()) { const checksum = createHash("sha256").update(await readFile(join(dir,name))).digest("hex"); const row=ledger.rows[index]; if(row?.name!==name||row.checksum.trim()!==checksum) throw new Error(`migration ledger mismatch for ${name}`); }
  } finally { await client.end(); }
}
void main().catch((error: unknown) => { console.error(error); process.exitCode = 1; });