-- Immutable clean-install baseline.  This is intentionally pre-thumbnail (Step 15).
create extension if not exists pgcrypto;

create type organization_status as enum ('provisioning','active','suspended','failed');
create type membership_status as enum ('invited','active','suspended');
create type provider_tenant_space_state as enum ('creating','created');
create type video_status as enum ('created','uploading','processing','ready','error');
create type video_visibility as enum ('private','unlisted','public');

create table plans (id uuid primary key default gen_random_uuid(), code text not null unique, name text not null, storage_limit_gb integer not null, entitlements jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table organizations (id uuid primary key default gen_random_uuid(), name text not null, slug text not null, status organization_status not null default 'provisioning', plan_id uuid not null references plans(id), storage_used_bytes bigint not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create unique index organizations_slug_idx on organizations(slug);
create index organizations_plan_idx on organizations(plan_id);
create table organization_customization (organization_id uuid primary key references organizations(id) on delete cascade, player_accent text not null default '#6C5CE7', player_control_foreground text not null default '#FFFFFF', player_control_background text not null default '#111827', logo_initials text not null default 'V', logo_object_key text, watermark_object_key text, poster_treatment text not null default 'default', custom_domain text, custom_domain_verified boolean not null default false, updated_at timestamptz not null default now());

create table users (id uuid primary key default gen_random_uuid(), email text not null, name text not null, email_verified boolean not null default false, image text, email_verified_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create unique index users_email_idx on users(email);
create table sessions (id uuid primary key default gen_random_uuid(), expires_at timestamptz not null, token text not null unique, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), ip_address text, user_agent text, user_id uuid not null references users(id) on delete cascade);
create index sessions_user_idx on sessions(user_id);
create table accounts (id uuid primary key default gen_random_uuid(), issuer text not null, account_id text not null, provider_id text not null, user_id uuid not null references users(id) on delete cascade, access_token text, refresh_token text, id_token text, access_token_expires_at timestamptz, refresh_token_expires_at timestamptz, scope text, password text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index accounts_user_idx on accounts(user_id); create unique index accounts_issuer_account_idx on accounts(issuer,account_id);
create table verifications (id uuid primary key default gen_random_uuid(), identifier text not null, value text not null, expires_at timestamptz not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index verifications_identifier_idx on verifications(identifier);
create table permission_groups (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, name text not null, description text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create unique index permission_groups_org_name_idx on permission_groups(organization_id,name); create index permission_groups_org_idx on permission_groups(organization_id);
create table permissions (key text primary key, description text not null);
create table group_permissions (group_id uuid not null references permission_groups(id) on delete cascade, permission_key text not null references permissions(key) on delete cascade, primary key(group_id,permission_key));
create table memberships (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, user_id uuid not null references users(id) on delete cascade, group_id uuid not null references permission_groups(id), status membership_status not null default 'active', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create unique index memberships_org_user_idx on memberships(organization_id,user_id); create index memberships_user_idx on memberships(user_id);
create table invitations (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, email text not null, group_id uuid not null references permission_groups(id), token_hash text not null unique, invited_by_user_id uuid not null references users(id), expires_at timestamptz not null, accepted_at timestamptz, created_at timestamptz not null default now());
create index invitations_org_idx on invitations(organization_id);

create table provider_accounts (id uuid primary key default gen_random_uuid(), provider_key text not null, label text not null, external_account_id text, encrypted_credentials text not null, zone_count_cached integer not null default 0, max_zones integer not null, accepting_new_tenants boolean not null default true, created_at timestamptz not null default now());
create index provider_accounts_capacity_idx on provider_accounts(provider_key,accepting_new_tenants);
create table provider_tenant_spaces (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, provider_account_id uuid not null references provider_accounts(id), provider_space_id text, idempotency_key text not null, encrypted_credentials text, metadata jsonb not null default '{}'::jsonb, external_call_claim uuid, external_call_claimed_at timestamptz, reconciliation_required boolean not null default false, state provider_tenant_space_state not null default 'creating', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create unique index provider_tenant_spaces_org_idx on provider_tenant_spaces(organization_id); create unique index provider_tenant_spaces_provider_space_idx on provider_tenant_spaces(provider_account_id,provider_space_id);
create table organization_entitlement_overrides (organization_id uuid not null references organizations(id) on delete cascade, key text not null, value jsonb not null);
create unique index entitlement_overrides_org_key_idx on organization_entitlement_overrides(organization_id,key);
create table webhook_events (id uuid primary key default gen_random_uuid(), provider_key text not null, receipt_digest text not null, provider_event_id text not null, provider_account_id uuid references provider_accounts(id), provider_tenant_space_id text, provider_asset_id text, organization_id uuid references organizations(id) on delete set null, owned_video_id uuid, verification_state text not null, processing_state text not null, diagnostic_code text, signature_valid boolean not null, payload jsonb not null default '{}'::jsonb, error text, verified_at timestamptz, claimed_at timestamptz, processed_at timestamptz, embed_enqueued_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create unique index webhook_events_provider_digest_idx on webhook_events(provider_key,receipt_digest); create index webhook_events_reconciliation_idx on webhook_events(processing_state,created_at);
create table embed_generation_outbox (id uuid primary key default gen_random_uuid(), webhook_event_id uuid not null references webhook_events(id) on delete cascade, video_id uuid not null, state text not null default 'pending', dispatch_claim uuid, claimed_at timestamptz, attempted_at timestamptz, dispatched_at timestamptz, completed_at timestamptz, attempts integer not null default 0, diagnostic_code text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create unique index embed_generation_outbox_receipt_video_idx on embed_generation_outbox(webhook_event_id,video_id); create index embed_generation_outbox_pending_idx on embed_generation_outbox(state,created_at);
create table audit_logs (id uuid primary key default gen_random_uuid(), organization_id uuid references organizations(id) on delete set null, actor_user_id uuid references users(id) on delete set null, action text not null, subject_type text not null, subject_id text, subject_label text not null, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create index audit_logs_org_time_idx on audit_logs(organization_id,created_at);

create table folders (id uuid not null default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, parent_id uuid, name text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint folders_org_id_pk primary key(organization_id,id), constraint folders_org_parent_fk foreign key(organization_id,parent_id) references folders(organization_id,id) on delete restrict, constraint folders_not_self_parent_check check(parent_id is null or parent_id <> id), constraint folders_name_normalized_check check(name=btrim(name) and char_length(name) between 1 and 120));
create unique index folders_org_root_name_ci_idx on folders(organization_id,lower(name)) where parent_id is null; create unique index folders_org_parent_name_ci_idx on folders(organization_id,parent_id,lower(name)) where parent_id is not null; create index folders_org_idx on folders(organization_id); create index folders_org_parent_idx on folders(organization_id,parent_id);
create table videos (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, folder_id uuid, title text not null, description text not null default '', status video_status not null default 'created', visibility video_visibility not null default 'private', duration_seconds integer not null default 0, thumbnail_color text not null default '#5B5BD6', provider_key text, provider_video_id text, provider_account_id uuid references provider_accounts(id), provider_tenant_space_id text, provider_asset_id text, upload_idempotency_key text, upload_failure_detail text, upload_source_bytes integer, upload_source_file_name text, upload_source_content_type text, reserved_bytes integer not null default 0, quota_released_at timestamptz, reservation_expires_at timestamptz, asset_creation_claim uuid, asset_creation_claimed_at timestamptz, deletion_claim uuid, deletion_claimed_at timestamptz, reconciliation_required text, initialization_retryable boolean not null default false, master_storage_key text, master_archived_at timestamptz, tags text[] not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint videos_org_folder_fk foreign key(organization_id,folder_id) references folders(organization_id,id) on delete restrict);
create index videos_org_created_idx on videos(organization_id,created_at); create index videos_org_status_idx on videos(organization_id,status); create index videos_org_folder_idx on videos(organization_id,folder_id); create unique index videos_org_upload_idempotency_idx on videos(organization_id,upload_idempotency_key); create unique index videos_private_provider_asset_idx on videos(provider_account_id,provider_tenant_space_id,provider_asset_id);
create table video_embeds (video_id uuid primary key references videos(id) on delete cascade, embed_path text not null, generation_version integer not null, generation_status text not null, generated_metadata jsonb not null, generated_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table video_analytics_rollups (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, video_id uuid not null references videos(id) on delete cascade, day text not null, plays integer not null default 0, watch_time_seconds integer not null default 0, completion_rate double precision not null default 0);
create unique index video_rollups_video_day_idx on video_analytics_rollups(video_id,day);
create table playback_events (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, video_id uuid not null references videos(id) on delete cascade, session_id uuid not null, event_type text not null, position_seconds double precision not null default 0, metadata jsonb not null default '{}'::jsonb, occurred_at timestamptz not null default now());
create index playback_events_org_time_idx on playback_events(organization_id,occurred_at);

do $$ begin if not exists (select 1 from pg_roles where rolname='vid_app') then create role vid_app nologin; end if; end $$;
grant usage on schema public to vid_app;
grant select,insert,update,delete on all tables in schema public to vid_app;
grant usage,select on all sequences in schema public to vid_app;
alter default privileges in schema public grant select,insert,update,delete on tables to vid_app;
alter default privileges in schema public grant usage,select on sequences to vid_app;
do $$ declare t text; begin foreach t in array array['organization_customization','permission_groups','memberships','invitations','folders','videos','video_analytics_rollups','playback_events','provider_tenant_spaces','organization_entitlement_overrides','audit_logs'] loop execute format('alter table %I enable row level security',t); execute format('create policy tenant_isolation on %I for all to vid_app using (organization_id = nullif(current_setting(''app.organization_id'', true), '''')::uuid) with check (organization_id = nullif(current_setting(''app.organization_id'', true), '''')::uuid)',t); end loop; end $$;